{% set name = "gmatelastoplastic" %}
{% set version = "0.2.1" %}
{% set sha256 = "c6a2d10c5ebc0a85c49487c474a1f42ccc1301edbdf85ac0cd6b878eba37a844" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlastic/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
    - gmattensor
    - gmatelastic
  run:
    - xtensor
    - gmattensor
    - gmatelastic

test:
  commands:
    - test -d ${PREFIX}/include/GMatElastoPlastic  # [unix]
    - test -f ${PREFIX}/include/GMatElastoPlastic/Cartesian3d.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/GMatElastoPlastic/GMatElastoPlasticConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GMatElastoPlastic\Cartesian3d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\GMatElastoPlasticConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/GMatElastoPlastic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic material model (C++ header-only library).
  description: Elasto-plastic material model (C++ header-only library).
  doc_url: https://github.com/tdegeus/GMatElastoPlastic
  dev_url: https://github.com/tdegeus/GMatElastoPlastic

extra:
  recipe-maintainers:
    - tdegeus
