{% set name = "gmatelastoplastic" %}
{% set version = "0.1.0" %}
{% set sha256 = "e66347d1c1e596da67069f618752585d94e4dca10fcb3a11cef5232d1fdf7d8a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlastic/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  run:
    - xtensor

test:
  commands:
    - test -d ${PREFIX}/include/GMatElastoPlastic  # [unix]
    - test -f ${PREFIX}/include/GMatElastoPlastic/Cartesian3d.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/GMatElastoPlastic/GMatElastoPlasticConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GMatElastoPlastic\Cartesian3d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\GMatElastoPlasticConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/GMatElastoPlastic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Elasto-plastic material model (C++ header-only library).'
  description: 'Elasto-plastic material model (C++ header-only library).'
  doc_url: https://github.com/tdegeus/GMatElastoPlastic
  dev_url: https://github.com/tdegeus/GMatElastoPlastic

extra:
  recipe-maintainers:
    - tdegeus
